# Change these first
owner: minifast # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Minifast
    url: https://www.minifast.co
  - name: Minstry of Velocity
    url: https://www.ministryofvelocity.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Minifast Status
  introMessage: |
    <div style="padding-bottom:56.25%; position:relative; display:block; width: 100%">
      <iframe width="100%" height="100%" style="position:absolute; top:0; left: 0" src="https://dashboards.calitp.org/public/dashboard/a5472b56-562c-49e9-bef1-47bdac6931c7" frameborder="0" allowtransparency allowfullscreen></iframe>
    </div>
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
